/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beeasy_web_core_Chakra */

#ifndef _Included_com_beeasy_web_core_Chakra
#define _Included_com_beeasy_web_core_Chakra
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_beeasy_web_core_Chakra
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_beeasy_web_core_Chakra_start
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
